// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

public interface GetPoIntegrityTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetPoIntegrityTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes k1 = 1;</code>
   * @return The k1.
   */
  com.google.protobuf.ByteString getK1();

  /**
   * <code>int32 b = 2;</code>
   * @return The b.
   */
  int getB();

  /**
   * <code>bytes k2 = 3;</code>
   * @return The k2.
   */
  com.google.protobuf.ByteString getK2();

  /**
   * <code>bytes d = 4;</code>
   * @return The d.
   */
  com.google.protobuf.ByteString getD();

  /**
   * <code>bytes e = 5;</code>
   * @return The e.
   */
  com.google.protobuf.ByteString getE();
}
