// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

/**
 * Protobuf type {@code GetPoIntegrityTokenResponse}
 */
public final class GetPoIntegrityTokenResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetPoIntegrityTokenResponse)
    GetPoIntegrityTokenResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPoIntegrityTokenResponse.newBuilder() to construct.
  private GetPoIntegrityTokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPoIntegrityTokenResponse() {
    k1_ = com.google.protobuf.ByteString.EMPTY;
    k2_ = com.google.protobuf.ByteString.EMPTY;
    d_ = com.google.protobuf.ByteString.EMPTY;
    e_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetPoIntegrityTokenResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetPoIntegrityTokenResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            k1_ = input.readBytes();
            break;
          }
          case 16: {

            b_ = input.readInt32();
            break;
          }
          case 26: {

            k2_ = input.readBytes();
            break;
          }
          case 34: {

            d_ = input.readBytes();
            break;
          }
          case 42: {

            e_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.android.mg.proto.POToken.internal_static_GetPoIntegrityTokenResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.android.mg.proto.POToken.internal_static_GetPoIntegrityTokenResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.android.mg.proto.GetPoIntegrityTokenResponse.class, com.google.android.mg.proto.GetPoIntegrityTokenResponse.Builder.class);
  }

  public static final int K1_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString k1_;
  /**
   * <code>bytes k1 = 1;</code>
   * @return The k1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getK1() {
    return k1_;
  }

  public static final int B_FIELD_NUMBER = 2;
  private int b_;
  /**
   * <code>int32 b = 2;</code>
   * @return The b.
   */
  @java.lang.Override
  public int getB() {
    return b_;
  }

  public static final int K2_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString k2_;
  /**
   * <code>bytes k2 = 3;</code>
   * @return The k2.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getK2() {
    return k2_;
  }

  public static final int D_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString d_;
  /**
   * <code>bytes d = 4;</code>
   * @return The d.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getD() {
    return d_;
  }

  public static final int E_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString e_;
  /**
   * <code>bytes e = 5;</code>
   * @return The e.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getE() {
    return e_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!k1_.isEmpty()) {
      output.writeBytes(1, k1_);
    }
    if (b_ != 0) {
      output.writeInt32(2, b_);
    }
    if (!k2_.isEmpty()) {
      output.writeBytes(3, k2_);
    }
    if (!d_.isEmpty()) {
      output.writeBytes(4, d_);
    }
    if (!e_.isEmpty()) {
      output.writeBytes(5, e_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!k1_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, k1_);
    }
    if (b_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, b_);
    }
    if (!k2_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, k2_);
    }
    if (!d_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, d_);
    }
    if (!e_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, e_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.android.mg.proto.GetPoIntegrityTokenResponse)) {
      return super.equals(obj);
    }
    com.google.android.mg.proto.GetPoIntegrityTokenResponse other = (com.google.android.mg.proto.GetPoIntegrityTokenResponse) obj;

    if (!getK1()
        .equals(other.getK1())) return false;
    if (getB()
        != other.getB()) return false;
    if (!getK2()
        .equals(other.getK2())) return false;
    if (!getD()
        .equals(other.getD())) return false;
    if (!getE()
        .equals(other.getE())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + K1_FIELD_NUMBER;
    hash = (53 * hash) + getK1().hashCode();
    hash = (37 * hash) + B_FIELD_NUMBER;
    hash = (53 * hash) + getB();
    hash = (37 * hash) + K2_FIELD_NUMBER;
    hash = (53 * hash) + getK2().hashCode();
    hash = (37 * hash) + D_FIELD_NUMBER;
    hash = (53 * hash) + getD().hashCode();
    hash = (37 * hash) + E_FIELD_NUMBER;
    hash = (53 * hash) + getE().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.android.mg.proto.GetPoIntegrityTokenResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetPoIntegrityTokenResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetPoIntegrityTokenResponse)
      com.google.android.mg.proto.GetPoIntegrityTokenResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.android.mg.proto.POToken.internal_static_GetPoIntegrityTokenResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.android.mg.proto.POToken.internal_static_GetPoIntegrityTokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.android.mg.proto.GetPoIntegrityTokenResponse.class, com.google.android.mg.proto.GetPoIntegrityTokenResponse.Builder.class);
    }

    // Construct using com.google.android.mg.proto.GetPoIntegrityTokenResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      k1_ = com.google.protobuf.ByteString.EMPTY;

      b_ = 0;

      k2_ = com.google.protobuf.ByteString.EMPTY;

      d_ = com.google.protobuf.ByteString.EMPTY;

      e_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.android.mg.proto.POToken.internal_static_GetPoIntegrityTokenResponse_descriptor;
    }

    @java.lang.Override
    public com.google.android.mg.proto.GetPoIntegrityTokenResponse getDefaultInstanceForType() {
      return com.google.android.mg.proto.GetPoIntegrityTokenResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.android.mg.proto.GetPoIntegrityTokenResponse build() {
      com.google.android.mg.proto.GetPoIntegrityTokenResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.android.mg.proto.GetPoIntegrityTokenResponse buildPartial() {
      com.google.android.mg.proto.GetPoIntegrityTokenResponse result = new com.google.android.mg.proto.GetPoIntegrityTokenResponse(this);
      result.k1_ = k1_;
      result.b_ = b_;
      result.k2_ = k2_;
      result.d_ = d_;
      result.e_ = e_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.android.mg.proto.GetPoIntegrityTokenResponse) {
        return mergeFrom((com.google.android.mg.proto.GetPoIntegrityTokenResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.android.mg.proto.GetPoIntegrityTokenResponse other) {
      if (other == com.google.android.mg.proto.GetPoIntegrityTokenResponse.getDefaultInstance()) return this;
      if (other.getK1() != com.google.protobuf.ByteString.EMPTY) {
        setK1(other.getK1());
      }
      if (other.getB() != 0) {
        setB(other.getB());
      }
      if (other.getK2() != com.google.protobuf.ByteString.EMPTY) {
        setK2(other.getK2());
      }
      if (other.getD() != com.google.protobuf.ByteString.EMPTY) {
        setD(other.getD());
      }
      if (other.getE() != com.google.protobuf.ByteString.EMPTY) {
        setE(other.getE());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.android.mg.proto.GetPoIntegrityTokenResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.android.mg.proto.GetPoIntegrityTokenResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString k1_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes k1 = 1;</code>
     * @return The k1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getK1() {
      return k1_;
    }
    /**
     * <code>bytes k1 = 1;</code>
     * @param value The k1 to set.
     * @return This builder for chaining.
     */
    public Builder setK1(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      k1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes k1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearK1() {
      
      k1_ = getDefaultInstance().getK1();
      onChanged();
      return this;
    }

    private int b_ ;
    /**
     * <code>int32 b = 2;</code>
     * @return The b.
     */
    @java.lang.Override
    public int getB() {
      return b_;
    }
    /**
     * <code>int32 b = 2;</code>
     * @param value The b to set.
     * @return This builder for chaining.
     */
    public Builder setB(int value) {
      
      b_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 b = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearB() {
      
      b_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString k2_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes k2 = 3;</code>
     * @return The k2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getK2() {
      return k2_;
    }
    /**
     * <code>bytes k2 = 3;</code>
     * @param value The k2 to set.
     * @return This builder for chaining.
     */
    public Builder setK2(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      k2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes k2 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearK2() {
      
      k2_ = getDefaultInstance().getK2();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString d_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes d = 4;</code>
     * @return The d.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getD() {
      return d_;
    }
    /**
     * <code>bytes d = 4;</code>
     * @param value The d to set.
     * @return This builder for chaining.
     */
    public Builder setD(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      d_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes d = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearD() {
      
      d_ = getDefaultInstance().getD();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString e_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes e = 5;</code>
     * @return The e.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getE() {
      return e_;
    }
    /**
     * <code>bytes e = 5;</code>
     * @param value The e to set.
     * @return This builder for chaining.
     */
    public Builder setE(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      e_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes e = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearE() {
      
      e_ = getDefaultInstance().getE();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetPoIntegrityTokenResponse)
  }

  // @@protoc_insertion_point(class_scope:GetPoIntegrityTokenResponse)
  private static final com.google.android.mg.proto.GetPoIntegrityTokenResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.android.mg.proto.GetPoIntegrityTokenResponse();
  }

  public static com.google.android.mg.proto.GetPoIntegrityTokenResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPoIntegrityTokenResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetPoIntegrityTokenResponse>() {
    @java.lang.Override
    public GetPoIntegrityTokenResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetPoIntegrityTokenResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetPoIntegrityTokenResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPoIntegrityTokenResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.android.mg.proto.GetPoIntegrityTokenResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

