// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

public interface GetPoIntegrityTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetPoIntegrityTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 mode = 1;</code>
   * @return The mode.
   */
  int getMode();

  /**
   * <code>bytes dgResult = 2;</code>
   * @return The dgResult.
   */
  com.google.protobuf.ByteString getDgResult();

  /**
   * <code>bytes dgRandKey = 3;</code>
   * @return The dgRandKey.
   */
  com.google.protobuf.ByteString getDgRandKey();
}
