// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

/**
 * Protobuf type {@code Key}
 */
public final class Key extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Key)
    KeyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Key.newBuilder() to construct.
  private Key(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Key() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Key();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Key(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.android.mg.proto.KeyData.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(com.google.android.mg.proto.KeyData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            status_ = input.readInt32();
            break;
          }
          case 24: {

            keyId_ = input.readInt32();
            break;
          }
          case 32: {

            outputPrefixType_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.android.mg.proto.POToken.internal_static_Key_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.android.mg.proto.POToken.internal_static_Key_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.android.mg.proto.Key.class, com.google.android.mg.proto.Key.Builder.class);
  }

  public static final int DATA_FIELD_NUMBER = 1;
  private com.google.android.mg.proto.KeyData data_;
  /**
   * <code>.KeyData data = 1;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.KeyData data = 1;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.android.mg.proto.KeyData getData() {
    return data_ == null ? com.google.android.mg.proto.KeyData.getDefaultInstance() : data_;
  }
  /**
   * <code>.KeyData data = 1;</code>
   */
  @java.lang.Override
  public com.google.android.mg.proto.KeyDataOrBuilder getDataOrBuilder() {
    return getData();
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int KEYID_FIELD_NUMBER = 3;
  private int keyId_;
  /**
   * <code>int32 keyId = 3;</code>
   * @return The keyId.
   */
  @java.lang.Override
  public int getKeyId() {
    return keyId_;
  }

  public static final int OUTPUTPREFIXTYPE_FIELD_NUMBER = 4;
  private int outputPrefixType_;
  /**
   * <code>int32 outputPrefixType = 4;</code>
   * @return The outputPrefixType.
   */
  @java.lang.Override
  public int getOutputPrefixType() {
    return outputPrefixType_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (data_ != null) {
      output.writeMessage(1, getData());
    }
    if (status_ != 0) {
      output.writeInt32(2, status_);
    }
    if (keyId_ != 0) {
      output.writeInt32(3, keyId_);
    }
    if (outputPrefixType_ != 0) {
      output.writeInt32(4, outputPrefixType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getData());
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, status_);
    }
    if (keyId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, keyId_);
    }
    if (outputPrefixType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, outputPrefixType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.android.mg.proto.Key)) {
      return super.equals(obj);
    }
    com.google.android.mg.proto.Key other = (com.google.android.mg.proto.Key) obj;

    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (getStatus()
        != other.getStatus()) return false;
    if (getKeyId()
        != other.getKeyId()) return false;
    if (getOutputPrefixType()
        != other.getOutputPrefixType()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + KEYID_FIELD_NUMBER;
    hash = (53 * hash) + getKeyId();
    hash = (37 * hash) + OUTPUTPREFIXTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getOutputPrefixType();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.android.mg.proto.Key parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.Key parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.Key parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.Key parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.Key parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.Key parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.Key parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.Key parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.mg.proto.Key parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.Key parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.mg.proto.Key parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.Key parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.android.mg.proto.Key prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Key}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Key)
      com.google.android.mg.proto.KeyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.android.mg.proto.POToken.internal_static_Key_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.android.mg.proto.POToken.internal_static_Key_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.android.mg.proto.Key.class, com.google.android.mg.proto.Key.Builder.class);
    }

    // Construct using com.google.android.mg.proto.Key.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      status_ = 0;

      keyId_ = 0;

      outputPrefixType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.android.mg.proto.POToken.internal_static_Key_descriptor;
    }

    @java.lang.Override
    public com.google.android.mg.proto.Key getDefaultInstanceForType() {
      return com.google.android.mg.proto.Key.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.android.mg.proto.Key build() {
      com.google.android.mg.proto.Key result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.android.mg.proto.Key buildPartial() {
      com.google.android.mg.proto.Key result = new com.google.android.mg.proto.Key(this);
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      result.status_ = status_;
      result.keyId_ = keyId_;
      result.outputPrefixType_ = outputPrefixType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.android.mg.proto.Key) {
        return mergeFrom((com.google.android.mg.proto.Key)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.android.mg.proto.Key other) {
      if (other == com.google.android.mg.proto.Key.getDefaultInstance()) return this;
      if (other.hasData()) {
        mergeData(other.getData());
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.getKeyId() != 0) {
        setKeyId(other.getKeyId());
      }
      if (other.getOutputPrefixType() != 0) {
        setOutputPrefixType(other.getOutputPrefixType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.android.mg.proto.Key parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.android.mg.proto.Key) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.android.mg.proto.KeyData data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.android.mg.proto.KeyData, com.google.android.mg.proto.KeyData.Builder, com.google.android.mg.proto.KeyDataOrBuilder> dataBuilder_;
    /**
     * <code>.KeyData data = 1;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <code>.KeyData data = 1;</code>
     * @return The data.
     */
    public com.google.android.mg.proto.KeyData getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.google.android.mg.proto.KeyData.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.KeyData data = 1;</code>
     */
    public Builder setData(com.google.android.mg.proto.KeyData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.KeyData data = 1;</code>
     */
    public Builder setData(
        com.google.android.mg.proto.KeyData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.KeyData data = 1;</code>
     */
    public Builder mergeData(com.google.android.mg.proto.KeyData value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            com.google.android.mg.proto.KeyData.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.KeyData data = 1;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.KeyData data = 1;</code>
     */
    public com.google.android.mg.proto.KeyData.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.KeyData data = 1;</code>
     */
    public com.google.android.mg.proto.KeyDataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.google.android.mg.proto.KeyData.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.KeyData data = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.android.mg.proto.KeyData, com.google.android.mg.proto.KeyData.Builder, com.google.android.mg.proto.KeyDataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.android.mg.proto.KeyData, com.google.android.mg.proto.KeyData.Builder, com.google.android.mg.proto.KeyDataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private int status_ ;
    /**
     * <code>int32 status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private int keyId_ ;
    /**
     * <code>int32 keyId = 3;</code>
     * @return The keyId.
     */
    @java.lang.Override
    public int getKeyId() {
      return keyId_;
    }
    /**
     * <code>int32 keyId = 3;</code>
     * @param value The keyId to set.
     * @return This builder for chaining.
     */
    public Builder setKeyId(int value) {
      
      keyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 keyId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyId() {
      
      keyId_ = 0;
      onChanged();
      return this;
    }

    private int outputPrefixType_ ;
    /**
     * <code>int32 outputPrefixType = 4;</code>
     * @return The outputPrefixType.
     */
    @java.lang.Override
    public int getOutputPrefixType() {
      return outputPrefixType_;
    }
    /**
     * <code>int32 outputPrefixType = 4;</code>
     * @param value The outputPrefixType to set.
     * @return This builder for chaining.
     */
    public Builder setOutputPrefixType(int value) {
      
      outputPrefixType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 outputPrefixType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputPrefixType() {
      
      outputPrefixType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Key)
  }

  // @@protoc_insertion_point(class_scope:Key)
  private static final com.google.android.mg.proto.Key DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.android.mg.proto.Key();
  }

  public static com.google.android.mg.proto.Key getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Key>
      PARSER = new com.google.protobuf.AbstractParser<Key>() {
    @java.lang.Override
    public Key parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Key(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Key> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Key> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.android.mg.proto.Key getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

