// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

public interface KeyDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:KeyData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string typeUrl = 1;</code>
   * @return The typeUrl.
   */
  java.lang.String getTypeUrl();
  /**
   * <code>string typeUrl = 1;</code>
   * @return The bytes for typeUrl.
   */
  com.google.protobuf.ByteString
      getTypeUrlBytes();

  /**
   * <code>.CipherKey value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.CipherKey value = 2;</code>
   * @return The value.
   */
  com.google.android.mg.proto.CipherKey getValue();
  /**
   * <code>.CipherKey value = 2;</code>
   */
  com.google.android.mg.proto.CipherKeyOrBuilder getValueOrBuilder();

  /**
   * <code>int32 keyMaterialType = 3;</code>
   * @return The keyMaterialType.
   */
  int getKeyMaterialType();
}
