// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

public interface KeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Key)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.KeyData data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.KeyData data = 1;</code>
   * @return The data.
   */
  com.google.android.mg.proto.KeyData getData();
  /**
   * <code>.KeyData data = 1;</code>
   */
  com.google.android.mg.proto.KeyDataOrBuilder getDataOrBuilder();

  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>int32 keyId = 3;</code>
   * @return The keyId.
   */
  int getKeyId();

  /**
   * <code>int32 outputPrefixType = 4;</code>
   * @return The outputPrefixType.
   */
  int getOutputPrefixType();
}
