// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

public interface KeySetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:KeySet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 primaryKeyId = 1;</code>
   * @return The primaryKeyId.
   */
  int getPrimaryKeyId();

  /**
   * <code>repeated .Key keyList = 2;</code>
   */
  java.util.List<com.google.android.mg.proto.Key> 
      getKeyListList();
  /**
   * <code>repeated .Key keyList = 2;</code>
   */
  com.google.android.mg.proto.Key getKeyList(int index);
  /**
   * <code>repeated .Key keyList = 2;</code>
   */
  int getKeyListCount();
  /**
   * <code>repeated .Key keyList = 2;</code>
   */
  java.util.List<? extends com.google.android.mg.proto.KeyOrBuilder> 
      getKeyListOrBuilderList();
  /**
   * <code>repeated .Key keyList = 2;</code>
   */
  com.google.android.mg.proto.KeyOrBuilder getKeyListOrBuilder(
      int index);
}
