// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

/**
 * Protobuf type {@code KeySet}
 */
public final class KeySet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:KeySet)
    KeySetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KeySet.newBuilder() to construct.
  private KeySet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KeySet() {
    keyList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KeySet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KeySet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            primaryKeyId_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              keyList_ = new java.util.ArrayList<com.google.android.mg.proto.Key>();
              mutable_bitField0_ |= 0x00000001;
            }
            keyList_.add(
                input.readMessage(com.google.android.mg.proto.Key.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        keyList_ = java.util.Collections.unmodifiableList(keyList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.android.mg.proto.POToken.internal_static_KeySet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.android.mg.proto.POToken.internal_static_KeySet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.android.mg.proto.KeySet.class, com.google.android.mg.proto.KeySet.Builder.class);
  }

  public static final int PRIMARYKEYID_FIELD_NUMBER = 1;
  private int primaryKeyId_;
  /**
   * <code>int32 primaryKeyId = 1;</code>
   * @return The primaryKeyId.
   */
  @java.lang.Override
  public int getPrimaryKeyId() {
    return primaryKeyId_;
  }

  public static final int KEYLIST_FIELD_NUMBER = 2;
  private java.util.List<com.google.android.mg.proto.Key> keyList_;
  /**
   * <code>repeated .Key keyList = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.android.mg.proto.Key> getKeyListList() {
    return keyList_;
  }
  /**
   * <code>repeated .Key keyList = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.android.mg.proto.KeyOrBuilder> 
      getKeyListOrBuilderList() {
    return keyList_;
  }
  /**
   * <code>repeated .Key keyList = 2;</code>
   */
  @java.lang.Override
  public int getKeyListCount() {
    return keyList_.size();
  }
  /**
   * <code>repeated .Key keyList = 2;</code>
   */
  @java.lang.Override
  public com.google.android.mg.proto.Key getKeyList(int index) {
    return keyList_.get(index);
  }
  /**
   * <code>repeated .Key keyList = 2;</code>
   */
  @java.lang.Override
  public com.google.android.mg.proto.KeyOrBuilder getKeyListOrBuilder(
      int index) {
    return keyList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (primaryKeyId_ != 0) {
      output.writeInt32(1, primaryKeyId_);
    }
    for (int i = 0; i < keyList_.size(); i++) {
      output.writeMessage(2, keyList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (primaryKeyId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, primaryKeyId_);
    }
    for (int i = 0; i < keyList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, keyList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.android.mg.proto.KeySet)) {
      return super.equals(obj);
    }
    com.google.android.mg.proto.KeySet other = (com.google.android.mg.proto.KeySet) obj;

    if (getPrimaryKeyId()
        != other.getPrimaryKeyId()) return false;
    if (!getKeyListList()
        .equals(other.getKeyListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRIMARYKEYID_FIELD_NUMBER;
    hash = (53 * hash) + getPrimaryKeyId();
    if (getKeyListCount() > 0) {
      hash = (37 * hash) + KEYLIST_FIELD_NUMBER;
      hash = (53 * hash) + getKeyListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.android.mg.proto.KeySet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.KeySet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.KeySet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.KeySet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.KeySet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.KeySet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.KeySet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.KeySet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.mg.proto.KeySet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.KeySet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.mg.proto.KeySet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.KeySet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.android.mg.proto.KeySet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code KeySet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:KeySet)
      com.google.android.mg.proto.KeySetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.android.mg.proto.POToken.internal_static_KeySet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.android.mg.proto.POToken.internal_static_KeySet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.android.mg.proto.KeySet.class, com.google.android.mg.proto.KeySet.Builder.class);
    }

    // Construct using com.google.android.mg.proto.KeySet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getKeyListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      primaryKeyId_ = 0;

      if (keyListBuilder_ == null) {
        keyList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        keyListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.android.mg.proto.POToken.internal_static_KeySet_descriptor;
    }

    @java.lang.Override
    public com.google.android.mg.proto.KeySet getDefaultInstanceForType() {
      return com.google.android.mg.proto.KeySet.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.android.mg.proto.KeySet build() {
      com.google.android.mg.proto.KeySet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.android.mg.proto.KeySet buildPartial() {
      com.google.android.mg.proto.KeySet result = new com.google.android.mg.proto.KeySet(this);
      int from_bitField0_ = bitField0_;
      result.primaryKeyId_ = primaryKeyId_;
      if (keyListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          keyList_ = java.util.Collections.unmodifiableList(keyList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.keyList_ = keyList_;
      } else {
        result.keyList_ = keyListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.android.mg.proto.KeySet) {
        return mergeFrom((com.google.android.mg.proto.KeySet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.android.mg.proto.KeySet other) {
      if (other == com.google.android.mg.proto.KeySet.getDefaultInstance()) return this;
      if (other.getPrimaryKeyId() != 0) {
        setPrimaryKeyId(other.getPrimaryKeyId());
      }
      if (keyListBuilder_ == null) {
        if (!other.keyList_.isEmpty()) {
          if (keyList_.isEmpty()) {
            keyList_ = other.keyList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKeyListIsMutable();
            keyList_.addAll(other.keyList_);
          }
          onChanged();
        }
      } else {
        if (!other.keyList_.isEmpty()) {
          if (keyListBuilder_.isEmpty()) {
            keyListBuilder_.dispose();
            keyListBuilder_ = null;
            keyList_ = other.keyList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            keyListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKeyListFieldBuilder() : null;
          } else {
            keyListBuilder_.addAllMessages(other.keyList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.android.mg.proto.KeySet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.android.mg.proto.KeySet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int primaryKeyId_ ;
    /**
     * <code>int32 primaryKeyId = 1;</code>
     * @return The primaryKeyId.
     */
    @java.lang.Override
    public int getPrimaryKeyId() {
      return primaryKeyId_;
    }
    /**
     * <code>int32 primaryKeyId = 1;</code>
     * @param value The primaryKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setPrimaryKeyId(int value) {
      
      primaryKeyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 primaryKeyId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrimaryKeyId() {
      
      primaryKeyId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.google.android.mg.proto.Key> keyList_ =
      java.util.Collections.emptyList();
    private void ensureKeyListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        keyList_ = new java.util.ArrayList<com.google.android.mg.proto.Key>(keyList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.android.mg.proto.Key, com.google.android.mg.proto.Key.Builder, com.google.android.mg.proto.KeyOrBuilder> keyListBuilder_;

    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public java.util.List<com.google.android.mg.proto.Key> getKeyListList() {
      if (keyListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(keyList_);
      } else {
        return keyListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public int getKeyListCount() {
      if (keyListBuilder_ == null) {
        return keyList_.size();
      } else {
        return keyListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public com.google.android.mg.proto.Key getKeyList(int index) {
      if (keyListBuilder_ == null) {
        return keyList_.get(index);
      } else {
        return keyListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public Builder setKeyList(
        int index, com.google.android.mg.proto.Key value) {
      if (keyListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyListIsMutable();
        keyList_.set(index, value);
        onChanged();
      } else {
        keyListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public Builder setKeyList(
        int index, com.google.android.mg.proto.Key.Builder builderForValue) {
      if (keyListBuilder_ == null) {
        ensureKeyListIsMutable();
        keyList_.set(index, builderForValue.build());
        onChanged();
      } else {
        keyListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public Builder addKeyList(com.google.android.mg.proto.Key value) {
      if (keyListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyListIsMutable();
        keyList_.add(value);
        onChanged();
      } else {
        keyListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public Builder addKeyList(
        int index, com.google.android.mg.proto.Key value) {
      if (keyListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyListIsMutable();
        keyList_.add(index, value);
        onChanged();
      } else {
        keyListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public Builder addKeyList(
        com.google.android.mg.proto.Key.Builder builderForValue) {
      if (keyListBuilder_ == null) {
        ensureKeyListIsMutable();
        keyList_.add(builderForValue.build());
        onChanged();
      } else {
        keyListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public Builder addKeyList(
        int index, com.google.android.mg.proto.Key.Builder builderForValue) {
      if (keyListBuilder_ == null) {
        ensureKeyListIsMutable();
        keyList_.add(index, builderForValue.build());
        onChanged();
      } else {
        keyListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public Builder addAllKeyList(
        java.lang.Iterable<? extends com.google.android.mg.proto.Key> values) {
      if (keyListBuilder_ == null) {
        ensureKeyListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keyList_);
        onChanged();
      } else {
        keyListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public Builder clearKeyList() {
      if (keyListBuilder_ == null) {
        keyList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        keyListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public Builder removeKeyList(int index) {
      if (keyListBuilder_ == null) {
        ensureKeyListIsMutable();
        keyList_.remove(index);
        onChanged();
      } else {
        keyListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public com.google.android.mg.proto.Key.Builder getKeyListBuilder(
        int index) {
      return getKeyListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public com.google.android.mg.proto.KeyOrBuilder getKeyListOrBuilder(
        int index) {
      if (keyListBuilder_ == null) {
        return keyList_.get(index);  } else {
        return keyListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public java.util.List<? extends com.google.android.mg.proto.KeyOrBuilder> 
         getKeyListOrBuilderList() {
      if (keyListBuilder_ != null) {
        return keyListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(keyList_);
      }
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public com.google.android.mg.proto.Key.Builder addKeyListBuilder() {
      return getKeyListFieldBuilder().addBuilder(
          com.google.android.mg.proto.Key.getDefaultInstance());
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public com.google.android.mg.proto.Key.Builder addKeyListBuilder(
        int index) {
      return getKeyListFieldBuilder().addBuilder(
          index, com.google.android.mg.proto.Key.getDefaultInstance());
    }
    /**
     * <code>repeated .Key keyList = 2;</code>
     */
    public java.util.List<com.google.android.mg.proto.Key.Builder> 
         getKeyListBuilderList() {
      return getKeyListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.android.mg.proto.Key, com.google.android.mg.proto.Key.Builder, com.google.android.mg.proto.KeyOrBuilder> 
        getKeyListFieldBuilder() {
      if (keyListBuilder_ == null) {
        keyListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.android.mg.proto.Key, com.google.android.mg.proto.Key.Builder, com.google.android.mg.proto.KeyOrBuilder>(
                keyList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        keyList_ = null;
      }
      return keyListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:KeySet)
  }

  // @@protoc_insertion_point(class_scope:KeySet)
  private static final com.google.android.mg.proto.KeySet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.android.mg.proto.KeySet();
  }

  public static com.google.android.mg.proto.KeySet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KeySet>
      PARSER = new com.google.protobuf.AbstractParser<KeySet>() {
    @java.lang.Override
    public KeySet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KeySet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KeySet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KeySet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.android.mg.proto.KeySet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

