// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

public final class POToken {
  private POToken() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CipherKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CipherKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KeyData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Key_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KeySet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KeySet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_POTokenInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_POTokenInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPoIntegrityTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPoIntegrityTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPoIntegrityTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPoIntegrityTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_POTokenResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_POTokenResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_POTokenResultWrap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_POTokenResultWrap_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPOToken.proto\"%\n\tCipherKey\022\t\n\001a\030\001 \001(\005\022" +
      "\r\n\005value\030\003 \001(\014\"N\n\007KeyData\022\017\n\007typeUrl\030\001 \001" +
      "(\t\022\031\n\005value\030\002 \001(\0132\n.CipherKey\022\027\n\017keyMate" +
      "rialType\030\003 \001(\005\"V\n\003Key\022\026\n\004data\030\001 \001(\0132\010.Ke" +
      "yData\022\016\n\006status\030\002 \001(\005\022\r\n\005keyId\030\003 \001(\005\022\030\n\020" +
      "outputPrefixType\030\004 \001(\005\"5\n\006KeySet\022\024\n\014prim" +
      "aryKeyId\030\001 \001(\005\022\025\n\007keyList\030\002 \003(\0132\004.Key\"t\n" +
      "\013POTokenInfo\022\t\n\001a\030\006 \001(\005\022\014\n\004time\030\001 \001(\005\022\021\n" +
      "\tinputData\030\002 \001(\014\022\017\n\007pkgName\030\003 \001(\t\022\025\n\rpkg" +
      "SignSha256\030\004 \001(\014\022\021\n\tpITokenK1\030\005 \001(\014\"O\n\032G" +
      "etPoIntegrityTokenRequest\022\014\n\004mode\030\001 \001(\005\022" +
      "\020\n\010dgResult\030\002 \001(\014\022\021\n\tdgRandKey\030\003 \001(\014\"V\n\033" +
      "GetPoIntegrityTokenResponse\022\n\n\002k1\030\001 \001(\014\022" +
      "\t\n\001b\030\002 \001(\005\022\n\n\002k2\030\003 \001(\014\022\t\n\001d\030\004 \001(\014\022\t\n\001e\030\005" +
      " \001(\014\"7\n\rPOTokenResult\022\023\n\013encryptData\030\001 \001" +
      "(\014\022\021\n\tpITokenK2\030\002 \001(\014\"1\n\021POTokenResultWr" +
      "ap\022\034\n\004data\030\001 \001(\0132\016.POTokenResultB\037\n\033com." +
      "google.android.mg.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CipherKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CipherKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CipherKey_descriptor,
        new java.lang.String[] { "A", "Value", });
    internal_static_KeyData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_KeyData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KeyData_descriptor,
        new java.lang.String[] { "TypeUrl", "Value", "KeyMaterialType", });
    internal_static_Key_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Key_descriptor,
        new java.lang.String[] { "Data", "Status", "KeyId", "OutputPrefixType", });
    internal_static_KeySet_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_KeySet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KeySet_descriptor,
        new java.lang.String[] { "PrimaryKeyId", "KeyList", });
    internal_static_POTokenInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_POTokenInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_POTokenInfo_descriptor,
        new java.lang.String[] { "A", "Time", "InputData", "PkgName", "PkgSignSha256", "PITokenK1", });
    internal_static_GetPoIntegrityTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetPoIntegrityTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPoIntegrityTokenRequest_descriptor,
        new java.lang.String[] { "Mode", "DgResult", "DgRandKey", });
    internal_static_GetPoIntegrityTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetPoIntegrityTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPoIntegrityTokenResponse_descriptor,
        new java.lang.String[] { "K1", "B", "K2", "D", "E", });
    internal_static_POTokenResult_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_POTokenResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_POTokenResult_descriptor,
        new java.lang.String[] { "EncryptData", "PITokenK2", });
    internal_static_POTokenResultWrap_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_POTokenResultWrap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_POTokenResultWrap_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
