// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

public interface POTokenResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POTokenResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes encryptData = 1;</code>
   * @return The encryptData.
   */
  com.google.protobuf.ByteString getEncryptData();

  /**
   * <code>bytes pITokenK2 = 2;</code>
   * @return The pITokenK2.
   */
  com.google.protobuf.ByteString getPITokenK2();
}
