// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

public interface POTokenResultWrapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POTokenResultWrap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.POTokenResult data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.POTokenResult data = 1;</code>
   * @return The data.
   */
  com.google.android.mg.proto.POTokenResult getData();
  /**
   * <code>.POTokenResult data = 1;</code>
   */
  com.google.android.mg.proto.POTokenResultOrBuilder getDataOrBuilder();
}
