// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

public interface POTokenInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POTokenInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 6;</code>
   * @return The a.
   */
  int getA();

  /**
   * <code>int32 time = 1;</code>
   * @return The time.
   */
  int getTime();

  /**
   * <code>bytes inputData = 2;</code>
   * @return The inputData.
   */
  com.google.protobuf.ByteString getInputData();

  /**
   * <code>string pkgName = 3;</code>
   * @return The pkgName.
   */
  java.lang.String getPkgName();
  /**
   * <code>string pkgName = 3;</code>
   * @return The bytes for pkgName.
   */
  com.google.protobuf.ByteString
      getPkgNameBytes();

  /**
   * <code>bytes pkgSignSha256 = 4;</code>
   * @return The pkgSignSha256.
   */
  com.google.protobuf.ByteString getPkgSignSha256();

  /**
   * <code>bytes pITokenK1 = 5;</code>
   * @return The pITokenK1.
   */
  com.google.protobuf.ByteString getPITokenK1();
}
