// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POToken.proto

package com.google.android.mg.proto;

/**
 * Protobuf type {@code POTokenInfo}
 */
public final class POTokenInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:POTokenInfo)
    POTokenInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use POTokenInfo.newBuilder() to construct.
  private POTokenInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private POTokenInfo() {
    inputData_ = com.google.protobuf.ByteString.EMPTY;
    pkgName_ = "";
    pkgSignSha256_ = com.google.protobuf.ByteString.EMPTY;
    pITokenK1_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new POTokenInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private POTokenInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            time_ = input.readInt32();
            break;
          }
          case 18: {

            inputData_ = input.readBytes();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            pkgName_ = s;
            break;
          }
          case 34: {

            pkgSignSha256_ = input.readBytes();
            break;
          }
          case 42: {

            pITokenK1_ = input.readBytes();
            break;
          }
          case 48: {

            a_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.android.mg.proto.POToken.internal_static_POTokenInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.android.mg.proto.POToken.internal_static_POTokenInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.android.mg.proto.POTokenInfo.class, com.google.android.mg.proto.POTokenInfo.Builder.class);
  }

  public static final int A_FIELD_NUMBER = 6;
  private int a_;
  /**
   * <code>int32 a = 6;</code>
   * @return The a.
   */
  @java.lang.Override
  public int getA() {
    return a_;
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private int time_;
  /**
   * <code>int32 time = 1;</code>
   * @return The time.
   */
  @java.lang.Override
  public int getTime() {
    return time_;
  }

  public static final int INPUTDATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString inputData_;
  /**
   * <code>bytes inputData = 2;</code>
   * @return The inputData.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getInputData() {
    return inputData_;
  }

  public static final int PKGNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object pkgName_;
  /**
   * <code>string pkgName = 3;</code>
   * @return The pkgName.
   */
  @java.lang.Override
  public java.lang.String getPkgName() {
    java.lang.Object ref = pkgName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pkgName_ = s;
      return s;
    }
  }
  /**
   * <code>string pkgName = 3;</code>
   * @return The bytes for pkgName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPkgNameBytes() {
    java.lang.Object ref = pkgName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pkgName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PKGSIGNSHA256_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString pkgSignSha256_;
  /**
   * <code>bytes pkgSignSha256 = 4;</code>
   * @return The pkgSignSha256.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPkgSignSha256() {
    return pkgSignSha256_;
  }

  public static final int PITOKENK1_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString pITokenK1_;
  /**
   * <code>bytes pITokenK1 = 5;</code>
   * @return The pITokenK1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPITokenK1() {
    return pITokenK1_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0) {
      output.writeInt32(1, time_);
    }
    if (!inputData_.isEmpty()) {
      output.writeBytes(2, inputData_);
    }
    if (!getPkgNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pkgName_);
    }
    if (!pkgSignSha256_.isEmpty()) {
      output.writeBytes(4, pkgSignSha256_);
    }
    if (!pITokenK1_.isEmpty()) {
      output.writeBytes(5, pITokenK1_);
    }
    if (a_ != 0) {
      output.writeInt32(6, a_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, time_);
    }
    if (!inputData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, inputData_);
    }
    if (!getPkgNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pkgName_);
    }
    if (!pkgSignSha256_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, pkgSignSha256_);
    }
    if (!pITokenK1_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, pITokenK1_);
    }
    if (a_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, a_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.android.mg.proto.POTokenInfo)) {
      return super.equals(obj);
    }
    com.google.android.mg.proto.POTokenInfo other = (com.google.android.mg.proto.POTokenInfo) obj;

    if (getA()
        != other.getA()) return false;
    if (getTime()
        != other.getTime()) return false;
    if (!getInputData()
        .equals(other.getInputData())) return false;
    if (!getPkgName()
        .equals(other.getPkgName())) return false;
    if (!getPkgSignSha256()
        .equals(other.getPkgSignSha256())) return false;
    if (!getPITokenK1()
        .equals(other.getPITokenK1())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + A_FIELD_NUMBER;
    hash = (53 * hash) + getA();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime();
    hash = (37 * hash) + INPUTDATA_FIELD_NUMBER;
    hash = (53 * hash) + getInputData().hashCode();
    hash = (37 * hash) + PKGNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPkgName().hashCode();
    hash = (37 * hash) + PKGSIGNSHA256_FIELD_NUMBER;
    hash = (53 * hash) + getPkgSignSha256().hashCode();
    hash = (37 * hash) + PITOKENK1_FIELD_NUMBER;
    hash = (53 * hash) + getPITokenK1().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.android.mg.proto.POTokenInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.POTokenInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.POTokenInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.POTokenInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.POTokenInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.android.mg.proto.POTokenInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.android.mg.proto.POTokenInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.POTokenInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.mg.proto.POTokenInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.POTokenInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.android.mg.proto.POTokenInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.android.mg.proto.POTokenInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.android.mg.proto.POTokenInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code POTokenInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:POTokenInfo)
      com.google.android.mg.proto.POTokenInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.android.mg.proto.POToken.internal_static_POTokenInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.android.mg.proto.POToken.internal_static_POTokenInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.android.mg.proto.POTokenInfo.class, com.google.android.mg.proto.POTokenInfo.Builder.class);
    }

    // Construct using com.google.android.mg.proto.POTokenInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      a_ = 0;

      time_ = 0;

      inputData_ = com.google.protobuf.ByteString.EMPTY;

      pkgName_ = "";

      pkgSignSha256_ = com.google.protobuf.ByteString.EMPTY;

      pITokenK1_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.android.mg.proto.POToken.internal_static_POTokenInfo_descriptor;
    }

    @java.lang.Override
    public com.google.android.mg.proto.POTokenInfo getDefaultInstanceForType() {
      return com.google.android.mg.proto.POTokenInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.android.mg.proto.POTokenInfo build() {
      com.google.android.mg.proto.POTokenInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.android.mg.proto.POTokenInfo buildPartial() {
      com.google.android.mg.proto.POTokenInfo result = new com.google.android.mg.proto.POTokenInfo(this);
      result.a_ = a_;
      result.time_ = time_;
      result.inputData_ = inputData_;
      result.pkgName_ = pkgName_;
      result.pkgSignSha256_ = pkgSignSha256_;
      result.pITokenK1_ = pITokenK1_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.android.mg.proto.POTokenInfo) {
        return mergeFrom((com.google.android.mg.proto.POTokenInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.android.mg.proto.POTokenInfo other) {
      if (other == com.google.android.mg.proto.POTokenInfo.getDefaultInstance()) return this;
      if (other.getA() != 0) {
        setA(other.getA());
      }
      if (other.getTime() != 0) {
        setTime(other.getTime());
      }
      if (other.getInputData() != com.google.protobuf.ByteString.EMPTY) {
        setInputData(other.getInputData());
      }
      if (!other.getPkgName().isEmpty()) {
        pkgName_ = other.pkgName_;
        onChanged();
      }
      if (other.getPkgSignSha256() != com.google.protobuf.ByteString.EMPTY) {
        setPkgSignSha256(other.getPkgSignSha256());
      }
      if (other.getPITokenK1() != com.google.protobuf.ByteString.EMPTY) {
        setPITokenK1(other.getPITokenK1());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.android.mg.proto.POTokenInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.android.mg.proto.POTokenInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int a_ ;
    /**
     * <code>int32 a = 6;</code>
     * @return The a.
     */
    @java.lang.Override
    public int getA() {
      return a_;
    }
    /**
     * <code>int32 a = 6;</code>
     * @param value The a to set.
     * @return This builder for chaining.
     */
    public Builder setA(int value) {
      
      a_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 a = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearA() {
      
      a_ = 0;
      onChanged();
      return this;
    }

    private int time_ ;
    /**
     * <code>int32 time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }
    /**
     * <code>int32 time = 1;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(int value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 time = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      
      time_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString inputData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes inputData = 2;</code>
     * @return The inputData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getInputData() {
      return inputData_;
    }
    /**
     * <code>bytes inputData = 2;</code>
     * @param value The inputData to set.
     * @return This builder for chaining.
     */
    public Builder setInputData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inputData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes inputData = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInputData() {
      
      inputData_ = getDefaultInstance().getInputData();
      onChanged();
      return this;
    }

    private java.lang.Object pkgName_ = "";
    /**
     * <code>string pkgName = 3;</code>
     * @return The pkgName.
     */
    public java.lang.String getPkgName() {
      java.lang.Object ref = pkgName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pkgName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pkgName = 3;</code>
     * @return The bytes for pkgName.
     */
    public com.google.protobuf.ByteString
        getPkgNameBytes() {
      java.lang.Object ref = pkgName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pkgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pkgName = 3;</code>
     * @param value The pkgName to set.
     * @return This builder for chaining.
     */
    public Builder setPkgName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pkgName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pkgName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPkgName() {
      
      pkgName_ = getDefaultInstance().getPkgName();
      onChanged();
      return this;
    }
    /**
     * <code>string pkgName = 3;</code>
     * @param value The bytes for pkgName to set.
     * @return This builder for chaining.
     */
    public Builder setPkgNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pkgName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString pkgSignSha256_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes pkgSignSha256 = 4;</code>
     * @return The pkgSignSha256.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPkgSignSha256() {
      return pkgSignSha256_;
    }
    /**
     * <code>bytes pkgSignSha256 = 4;</code>
     * @param value The pkgSignSha256 to set.
     * @return This builder for chaining.
     */
    public Builder setPkgSignSha256(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pkgSignSha256_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes pkgSignSha256 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPkgSignSha256() {
      
      pkgSignSha256_ = getDefaultInstance().getPkgSignSha256();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString pITokenK1_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes pITokenK1 = 5;</code>
     * @return The pITokenK1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPITokenK1() {
      return pITokenK1_;
    }
    /**
     * <code>bytes pITokenK1 = 5;</code>
     * @param value The pITokenK1 to set.
     * @return This builder for chaining.
     */
    public Builder setPITokenK1(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pITokenK1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes pITokenK1 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPITokenK1() {
      
      pITokenK1_ = getDefaultInstance().getPITokenK1();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:POTokenInfo)
  }

  // @@protoc_insertion_point(class_scope:POTokenInfo)
  private static final com.google.android.mg.proto.POTokenInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.android.mg.proto.POTokenInfo();
  }

  public static com.google.android.mg.proto.POTokenInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<POTokenInfo>
      PARSER = new com.google.protobuf.AbstractParser<POTokenInfo>() {
    @java.lang.Override
    public POTokenInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new POTokenInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<POTokenInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<POTokenInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.android.mg.proto.POTokenInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

